FROM openjdk:11
MAINTAINER rupesh@gmail.com
VOLUME /tmp
EXPOSE 8084
ARG JAR_FILE=target\employee-management-webapp-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} employee-management-webapp-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","target/employee-management-webapp-0.0.1-SNAPSHOT.jar"]